export const AppItems = [
    {
        title: "projects.loginsystem.title",
        desc: "projects.loginsystem.desc",
        toolsused: [
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg",
        ],
        url: "/images/Login-system.png",
        video: "/images/Login-system.mp4",
        index: "z-50",
        pagetitle: "projects.loginsystem.pagetitle",
        pagelink: "http://login-system-front-aflp2199.herokuapp.com/login",
        gitlink: "https://github.com/AFLP2199/login-system-frontend",
    },
    {
        title: "projects.photogallery.title",
        desc: "projects.photogallery.desc",
        toolsused: [
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg",
        ],
        url: "/images/PhotoGallery.png",
        video: "/images/PhotoGallery.mp4",
        index: "z-40",
        pagetitle: "projects.photogallery.pagetitle",
        pagelink: "https://aflp2199.github.io/PhotoGallery/",
        gitlink: "https://github.com/AFLP2199/PhotoGallery",
    },
    {
        title: "projects.moviesearchengine.title",
        desc: "projects.moviesearchengine.desc",
        toolsused: [
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jquery/jquery-original.svg",
        ],
        url: "/images/MovieSearch.png",
        video: "/images/MovieSearch.mp4",
        index: "z-30",
        pagetitle: "projects.moviesearchengine.pagetitle",
        pagelink: "https://aflp2199.github.io/MovieSearchEngine/index.html",
        gitlink: "https://github.com/AFLP2199/MovieSearchEngine",
    },
    {
        title: "projects.tipcalculatorapp.title",
        desc: "projects.tipcalculatorapp.desc",
        toolsused: [
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
        ],
        url: "/images/TipCalculatorApp.png",
        video: "/images/TipCalculatorApp.mp4",
        index: "z-20",
        pagetitle: "projects.tipcalculatorapp.pagetitle",
        pagelink: "https://aflp2199.github.io/TipCalculatorApp/",
        gitlink: "https://github.com/AFLP2199/TipCalculatorApp",
    },
    {
        title: "projects.simplecalculator.title",
        toolsused: [
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
        ],
        desc: "projects.simplecalculator.desc",
        url: "/images/Calculator.png",
        video: "/images/Calculator.mp4",
        index: "z-10",
        pagetitle: "projects.simplecalculator.pagetitle",
        pagelink: "https://aflp2199.github.io/SimpleCalculator/",
        gitlink: "https://github.com/AFLP2199/SimpleCalculator",
    },
];

export const WebItems = [
    {
        title: "projects.hackctf.title",
        toolsused: [
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jquery/jquery-original.svg",
        ],
        url: "/images/HackCTF.png",
        desc: "projects.hackctf.desc",
        video: "/images/HackCTF.mp4",
        index: "z-70",
        pagetitle: "projects.hackctf.pagetitle",
        pagelink: "https://hackctf.org/ctf/",
        gitlink: "#/",
    },
    {
        title: "projects.apinta.title",
        url: "/images/Apinta.png",
        toolsused: [
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jquery/jquery-original.svg",
        ],
        desc: "projects.apinta.desc",
        video: "/images/Apinta.mp4",
        index: "z-60",
        pagetitle: "projects.apinta.pagetitle",
        pagelink: "https://apintacastelar.com.ar/home/",
        gitlink: "#/",
    },
];
